version: '3.6'

services:
  mysql:
    image: mysql:8.0.26
    environment: 
      MYSQL_DATABASE: springblog
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3307"
    volumes:
      - /home/braians/desenvolvimento/Docker/Volumes/Mysql/lib/mysql
    networks:
      - app-network



  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge